### ISSUE TITLE
Worker class for DML queries

### ISSUE THREAD

**Issue by bsq-panagiotis** [google/crmint#105]
I think there's a nice feature that is missing. I couldn't find any workers available, which would allow someone to execute DML queries (e.g. DELETE). It would be really useful, as such a worker would allow someone to clear a BQ table, before importing new GA data with the GAToBQImporter.

I already tried to use the BQQueryLauncher worker class with a DELETE statement, but I'm getting the following error:

> Job: XXXX, Worker Class: BQQueryLauncher
> Execution failed: WorkerException: Cannot set destination table in jobs with DML statements

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
