### ISSUE TITLE
Deadline exceeded while waiting for HTTP response

### ISSUE THREAD

**Issue by benpowis** [google/crmint#107]
I have a pipeline job that has been failing for the last three days the following error:

Unexpected error: ConnectionError: ('Connection aborted.', HTTPException('Deadline exceeded while waiting for HTTP response from URL: https://www.googleapis.com/bigquery/v2/projects/PROJECT_NAME/jobs',))

This job has been running every day for many months without an issue and has remained unchanged, has there been some change to BigQuery that could cause this?

**Comment by Slony** [comment]
Hi @benpowis,

AFAIK, there were no recent updates in BigQuery API.

Can you please try to use Google API Explorer to [fetch the BigQuery job list](https://developers.google.com/apis-explorer/#p/bigquery/v2/bigquery.jobs.list) for the project that is used in your data pipeline and let me know if it works for you? This might help to pinpoint the issue.

Thanks!

**Comment by benpowis** [comment]
Hi @Slony 

I ran the API explorer but I can't see any jobs relating to the CRMint pipelines.

Interestingly it appears some of the error jobs did actually run, but not all. I can share the pipeline privately if this helps?

Ben

**Comment by benpowis** [comment]
Hi @Slony 

This issue is now affecting multiple pipelines intermittently, sometimes they run just fine and sometimes I get this error, causing the job to fail.

Do you have any suggestions on how we can troubleshoot?

Thanks,
Ben

**Comment by benpowis** [comment]
Could this error be related too https://stackoverflow.com/questions/14698119/httpexception-deadline-exceeded-while-waiting-for-http-response-from-url-dead ?

**Comment by Slony** [comment]
@benpowis thank you for investigating this issue and giving us a very useful hint about default 5 second timeout for `URLFetch` requests. The timeout has been increased to 300 seconds in [PR#109](https://github.com/google/crmint/pull/109).
