### ISSUE TITLE
Update frontend to Angular 8

### ISSUE THREAD

**Issue by adamread** [google/crmint#118]
CRMint is currently using Angular 4.4.6. To help with maintainability and to improve frontend performance, an update to the latest version of Angular (8.0 as of 2019-06-21) can be carried out.

**Comment by andgandolfi** [comment]
I've added a pull request with the upgrade to Angular 9: https://github.com/google/crmint/pull/169

**Comment by Slony** [comment]
Fixed with [PR#169: [Feature/118] Upgrading CRMint frontend to the last version of Angular (9)](https://github.com/google/crmint/pull/169)
