### ISSUE TITLE
Jobs get stuck with their last status.

### ISSUE THREAD

**Issue by osuarez-div** [google/crmint#149]
I am experiencing some issues when trying to run individual jobs inside a pipeline: the jobs are not changing its status and seems to be stucked. I tried to export and then import the pipeline but the same error occurred. Also I tried to redefine the same pipeline from scratch in a new Pipeline and I am still not able to run the jobs. 
The button 'Run Pipeline' seems to be stucked also.

How can I manage this issue? 
Could I reset CRMint somehow and try again to run the jobs?

**Comment by osuarez-div** [comment]
I found the problem finally in the logs. The issue was with one of the variables I was ussing, that was not well defined but the error doesn't seem to appear in the Pipeline graph (as the errors from the execution of the jobs), so I completely forgot to look in the logs.
Probably would be a nice feature to show this kind of errores also  in the in the graph of the Pipeline.

**Comment by Slony** [comment]
Hi @osuarez-div, thank you for creating this issue.

You can reset statuses of _all_ jobs in _all_ pipelines using the following command in your Cloud Shell:

```bash
crmint cloud reset
```

Please, be careful with this command as it resets statuses of _all_ jobs and _all_ pipeline regardless of their actual state. I mean, this command can lead to an abrupt stop of the running pipelines.

Can you please create a separate issue with a feature request for logging variables-related errors in the pipeline logs available in the web UI?
