### ISSUE TITLE
GADataImporter failure

### ISSUE THREAD

**Issue by goyalvishesh** [google/crmint#164]
Unexpected error: HttpError: <HttpError 400 when requesting https://www.googleapis.com/analytics/v3/management/accounts/xxx/webproperties/UA-xxx-1/customDataSources/xxx/deleteUploadData? returned "Invalid client data: Invalid argument: Can only delete upload if successfully processed or failed: JQe_TpBhS6Sg1bVi5sQg-w.">

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
