### ISSUE TITLE
Deploy Error in  Applying database migrations   & Sowing DB seeds  phases

### ISSUE THREAD

**Issue by GitLor** [google/crmint#166]
I followed the ufficial documentation  by running the following commands from the project cloud  shell:

_Install CRMint command-line.
bash <(curl -Ls https://raw.githubusercontent.com/google/crmint/master/scripts/install.sh) master
Create a stage definition for your environment.
crmint stages create
 Re-run the setup in case new elements are needed.
crmint cloud setup
 Deploy the updated App Engine services.
crmint cloud deploy_

During the "crmint cloud deploy"
phase, errors relating to the database were detected. (see attachment for details)
In particular I have two time this exception "_**sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'crmintapp'@'cloudsqlproxy~34.77.43.129' (using password: YES)")"**_ 

The strange thing is that the ip address used is not that of my mysql instance. If I try to repeat the deployment with another account I get an even different ip.

Note that the setting commands that generated the mysql instance and the app-engine instance were launched at two different times.

In fact, initially not being the owner of the project, the setup command was not able to generate the Appengine instance, while it was successful with the creation of the other services (including sql cloud).

Once the permissions of the owner of the project were purchased, the instance of the app engine was renewed, updated but the services already previously created.

We noticed that we were deleting the mysql instance, but from what we read for some days we would not be allowed to recreate a new instance within the same project with the same name. Is there any way to overcome this constraint?
We tried to delete the db within the instance, restore from other crmint project,  but this had no effect.

We would like if possible to avoid the creation of a new cloud project.
[crmint-deploy-error _ v2.txt](https://github.com/google/crmint/files/4257032/crmint-deploy-error._.v2.txt)
![crmint- screen console log](https://user-images.githubusercontent.com/48475121/75367056-fcb5eb80-58bf-11ea-8e00-190c04d39aac.JPG)
![crmint-screen](https://user-images.githubusercontent.com/48475121/75367062-fde71880-58bf-11ea-9560-d2697099eca5.JPG)
[crmint-deploy-error.txt](https://github.com/google/crmint/files/4257033/crmint-deploy-error.txt)

For an overall view of the problem, I attach the screens relating to the errors obtained by accessing the crmint application via browser, both from the interface and from the console.

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
