### ISSUE TITLE
Ensure the setup script fails on errors

### ISSUE THREAD

**Issue by achembarpu** [google/crmint#186]
Hey team,

Sometimes, the `install.sh` script fails at a line, but continues running - because `set -e` is not used [0]. I think this is worth adding to the script, to prevent partial/failed setups. With `set -ex`, we can even get easier debugging.

Thanks!

[0] [More about set -e](https://www.peterbe.com/plog/set-ex)

**Comment by nnajdova-git** [comment]
Example failure: 

bash <(curl -Ls https://raw.githubusercontent.com/google/crmint/master/scripts/install.sh) master
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2
-support
ERROR: cli/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
\nAdding a bash function to your /home/nnajdova/.bashrc file.
Reloading the shell

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
