### ISSUE TITLE
Branching based on success/fail doesn't work

### ISSUE THREAD

**Issue by zvizdo** [google/crmint#196]
I have a Commenter task set to fail, and then two flows out, one based on success and one based on fail.
The task execution stops when the initial task fails.
Screenshot: https://paste.pics/a0568ee1574f16e881192b1a24ad0808

I did notice if I only have the failing initial task, and then the next one executions on fail of the initial one (and no other branches) it does work and executes the second task too.

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
