### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by tyroneschiff** [google/crmint#198]
CRMint is returning 
`Unexpected error: UnboundLocalError: local variable 'status' referenced before assignment`
for the GADataImporter worker.

I'm attaching some screenshots of Logs from the UI as well as where this appears to be happening in the code.

![8Ep6ZxAdPqV33uu](https://user-images.githubusercontent.com/452271/97053354-c9138a00-1550-11eb-9959-000164620449.png)
![_upload](https://user-images.githubusercontent.com/452271/97053302-ad0fe880-1550-11eb-8b30-237d6fb287d1.png)

**Comment by aleinv18** [comment]
same issue today

**Comment by tyroneschiff** [comment]
This appears to have been related to an upstream Google Analytics API issue. More details [here](https://issuetracker.google.com/issues/171493243).

This does not appear to be impacting GADataImporter since yesterday. Closing this issue out.
