### ISSUE TITLE
Cron doesnt work

### ISSUE THREAD

**Issue by andrzejeob** [google/crmint#208]
Hello. Thanks for a powerful and useful tool. We have faced problem with cron. It doesn't deploy any jobs, what do we need to check to run it?

**Comment by Slony** [comment]
Hi @andrzejeob. Please check if an every-minute job exists in the [App Engine's Cron service](https://console.cloud.google.com/appengine/cronjobs):

![crmint-cron](https://user-images.githubusercontent.com/797778/99538693-3b875680-29a5-11eb-907f-c096d1aec5a3.png)

**Comment by andrzejeob** [comment]
Hello,
I got this, but with failure:
![obraz](https://user-images.githubusercontent.com/74649996/99540232-8efea200-29af-11eb-8607-be3db47fc7a8.png)

What can be wrong?

**Comment by Slony** [comment]
Can you share the logs please?

**Comment by andrzejeob** [comment]
There is 500 error:
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.appengine.logging.v1.RequestLog",
    "appId": " my app",
    "versionId": "v1",
    "requestId": "5fb52fe800ff06a11f1ca32ba40001657e656f62757769652d31383130313300016a6f622d736572766963653a7631000100",
    "ip": "0.1.0.1",
    "startTime": "2020-11-18T14:30:00.434463Z",
    "endTime": "2020-11-18T14:30:00.543524Z",
    "latency": "0.109061s",
    "megaCycles": "2300",
    "method": "GET",
    "resource": "/cron",
    "httpVersion": "HTTP/1.1",
    "status": 500,
    "responseSize": "121",
    "userAgent": "AppEngine-Google; (+http://code.google.com/appengine)",
    "urlMapEntry": "run_jbackend.app",
    "host": "job-service.myproject.appspot.com",
    "cost": 1.3522e-8,
    "taskQueueName": "__cron",
    "taskName": "fd981b7922b66a99b7f2301135f07685",
    "finished": true,
    "instanceId": "00c61b117ccac3076df38a73610368e5f3aaa8663455add39a12febd02de5ad515cfaad522b96c107e4abd70630d91e081d730d76043969a9d688ea7ff2a2ef51a346d28e72dd3",
    "line":

**Comment by Slony** [comment]
@andrzejeob do your pipelines run successfully when you start them manually?

**Comment by andrzejeob** [comment]
Yes, they are.

**Comment by Slony** [comment]
Could you check if the cron strings used in the schedules of the scheduled pipelines conform to the [Cron Format](http://www.nncron.ru/help/EN/working/cron-format.htm) please?

![crmit-schedules](https://user-images.githubusercontent.com/797778/99634873-16442800-2a39-11eb-88f5-b263675aec1c.png)

**Comment by andrzejeob** [comment]
Yes, they do, but there is an error 500 even when there is no job at crmint (because cron on cloud server runs every minute).

**Comment by Slony** [comment]
CRMint's cron job in App Engine calls [this](https://github.com/google/crmint/blob/dev/backends/jbackend/cron/views.py#L43) method in the [`jobs-service`](https://console.cloud.google.com/appengine/versions?serviceId=job-service) every minute. As you can see in the code, this method does nothing but compares the scheduled pipelines' cron strings with the current time and runs the pipelines if there is a match. So, if the pipelines run successfully when you start them manually, then there should be something wrong with the cron strings matching part.

Could you share the [`job-service` logs](https://console.cloud.google.com/logs/viewer?resource=gae_app%2Fmodule_id%2Fjob-service&expandAll=false&limitCustomFacetWidth=false&minLogLevel=0) please?

![job-service-logs](https://user-images.githubusercontent.com/797778/99637666-18a88100-2a3d-11eb-9fa7-65b05a853da0.png)

**Comment by andrzejeob** [comment]
There are mostly 500 errors:
![obraz](https://user-images.githubusercontent.com/74649996/99645197-341c8780-2a4f-11eb-85e8-6e020f12432f.png)

**Comment by Slony** [comment]
Would you mind unfolding one of the error messages please:

![99645197-341c8780-2a4f-11eb-85e8-6e020f12432f png (1011×674) 2020-11-19 09-50-33](https://user-images.githubusercontent.com/797778/99649979-c4a59880-2a4c-11eb-952e-99dd36fbe483.png)

It should reveal the Python stack trace like this one:

![stack-trace](https://user-images.githubusercontent.com/797778/99650705-aa1fef00-2a4d-11eb-84c7-a7d2d7ffcade.png)

**Comment by andrzejeob** [comment]
![obraz](https://user-images.githubusercontent.com/74649996/99651261-a349aa00-2a56-11eb-8a32-8a702c8b3726.png)

**Comment by Slony** [comment]
Can you please collapse nested fields clicking here:

![1](https://user-images.githubusercontent.com/797778/99651861-0c2d2400-2a4f-11eb-8851-eab7ecdf529f.png)

… and share a screenshot like this:

![2](https://user-images.githubusercontent.com/797778/99652086-45fe2a80-2a4f-11eb-9468-d7eabaa5954a.png)

**Comment by andrzejeob** [comment]
![obraz](https://user-images.githubusercontent.com/74649996/99655024-75b32f80-2a5b-11eb-8f9e-f4472b802c91.png)

**Comment by Slony** [comment]
please share the last few lines of the stack trace

**Comment by andrzejeob** [comment]
![obraz](https://user-images.githubusercontent.com/74649996/99666126-d9912480-2a6a-11eb-84cb-f53fbaa09290.png)

**Comment by andrzejeob** [comment]
![obraz](https://user-images.githubusercontent.com/74649996/99666174-e877d700-2a6a-11eb-9eaa-8de6329d4f26.png)

**Comment by Slony** [comment]
OK, you have a malformed cron string in one of the schedules for one of your pipelines: [`CrontierBadCronError`](https://github.com/kiorky/croniter/blob/master/src/croniter/croniter.py#L28)`(`[`cls.bas_length`](https://github.com/kiorky/croniter/blob/master/src/croniter/croniter.py#L88)`)` exception means "Exactly 5 or 6 columns has to be specified for iterator expression."

Please refer to the first lines of the log entry to learn what cron string is malformed and for what pipeline:

![1](https://user-images.githubusercontent.com/797778/99691675-647d1980-2a81-11eb-9318-3bb00b824c08.png)

Please refer to [Cron Format](http://www.nncron.ru/help/EN/working/cron-format.htm) for more details on the cron string format.

**Comment by andrzejeob** [comment]
Ok, I will check that.

**Comment by andrzejeob** [comment]
Now I've checked and eliminate every possible cron format mistake and I receive 200 status without errors:
![obraz](https://user-images.githubusercontent.com/74649996/99775058-f848f700-2b0e-11eb-9e29-acd293a784fe.png)

But still nothing is done by itself, I don't see it in logs:
![obraz](https://user-images.githubusercontent.com/74649996/99775175-22021e00-2b0f-11eb-9d7d-94ff77dcc1dc.png)

Maybe there is something wrong with permissions?
If I can manually start the pipe, there is no problem with pemissions?
Because I have one crmint on one project but I use tables in SQL from another project - but it works when I click manually.

**Comment by andrzejeob** [comment]
Only first job is running correctly with cron.

**Comment by andrzejeob** [comment]
Sorry, now when I refresh (by clicking off then on) each pipe, everyhing is working. Thanks for help.
