### ISSUE TITLE
BigQuery to Google Analytics pipeline

### ISSUE THREAD

**Issue by OugribeSara** [google/crmint#214]
Hi everyone ! 
I am trying to export customers segmentation in Google Analytics using « BQToStorageExporter » to export a BigQuery table to a CSV file and « GADataImporter » to import that CSV file into Google Analytics.
Google Analytics requires a specific header to import data (in my case ga:dimension2,ga:dimension1) but BigQuery doesn’t accept the symbol « : » in field names.
Any suggestions?

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
