### ISSUE TITLE
Installation not working, crmint cloud deploy fails with "Package 'rsa' requires a different Python" error

### ISSUE THREAD

**Issue by evil-shrike** [google/crmint#239]
Hi,

following the [Deployment guide](https://github.com/google/crmint/wiki/Deploy-CRMint-on-Google-Cloud-Platform) in a newly created project. 
I'm getting the following error on running `crmint cloud deploy` in my Cloud Shell:
```
ERROR: Package 'rsa' requires a different Python: 2.7.16 not in '>=3.5, <4'
```
Obviously in Cloud Shell I have Python 2.7 as default Python.

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
