### ISSUE TITLE
Move Cloud deploy scripts to main repo

### ISSUE THREAD

**Issue by Slony** [google/crmint#31]
It would be nice to have quick-start scripts in the main CRMint repo, wouldn't it?

- [deploy-dev.sh](https://gist.github.com/dulacp/0b6104e3b1b09adfd1e89aacd442cb62#file-deploy-dev-sh)
- [deploy-master.sh](https://gist.github.com/dulacp/0b6104e3b1b09adfd1e89aacd442cb62#file-deploy-master-sh)

**Comment by dulacp** [comment]
Completely agree with you!
PR#32 is approved and ready to be merged.
