### ISSUE TITLE
GAToBQImporter - All values are NULL in BigQuery

### ISSUE THREAD

**Issue by bmind** [google/crmint#33]
Hello team. I have just tested CRMINT and is an amazing tool for marketing automation in Google Cloud (we plan to use it and even develop some workers eg: connect to sftp client, grab all files and store them in Google Storage).

I have a little issue with: "**GAToBQImporter**".

I've setup the pipeline with a job that is using "**GAToBQImporter**" and everything works just fine (got the message with "Pipeline succeeded", all logs are great in stackdriver, in bigquery,  got all rows (3759 -  i've compared CRMINT results vs APIv4 GA vs Query Explorer) but all values are NULL). Am I'm doing something wrong?

**My schema for BigQuery "output" table is**:
[
  {
    "mode": "NULLABLE",
    "name": "field1",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "field2",
    "type": "STRING"
  },
  {
    "mode": "NULLABLE",
    "name": "field3",
    "type": "STRING"
  }
]

**Sample data inserted via CRMINT with GAToBQImporter in BigQuery output table**:

[
  {
    "field1": null, 
    "field2": null, 
    "field3": null
  }, 
  {
    "field1": null, 
    "field2": null, 
    "field3": null
  }, 
  {
    "field1": null, 
    "field2": null, 
    "field3": null
  }, 
  {
    "field1": null, 
    "field2": null, 
    "field3": null
  }, 
  {
    "field1": null, 
    "field2": null, 
    "field3": null
  }
..
..
..
..
]

**Job setup**:
"jobs": [
    {
      "hash_start_conditions": [],
      "worker_class": "GAToBQImporter",
      "params": [
        {
          "description": null,
          "value": "122591566",
          "label": null,
          "is_required": false,
          "type": "string_list",
          "name": "view_ids"
        },
        {
          "description": null,
          "value": "2018-08-01",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "start_date"
        },
        {
          "description": null,
          "value": "2018-08-05",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "end_date"
        },
        {
          "description": null,
          "value": false,
          "label": null,
          "is_required": false,
          "type": "boolean",
          "name": "day_by_day"
        },
        {
          "description": null,
          "value": "ga:users",
          "label": null,
          "is_required": false,
          "type": "string_list",
          "name": "metrics"
        },
        {
          "description": null,
          "value": "ga:source\nga:date",
          "label": null,
          "is_required": false,
          "type": "string_list",
          "name": "dimensions"
        },
        {
          "description": null,
          "value": "",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "filters"
        },
        {
          "description": null,
          "value": true,
          "label": null,
          "is_required": false,
          "type": "boolean",
          "name": "include_empty_rows"
        },
        {
          "description": null,
          "value": "BMIND",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "bq_project_id"
        },
        {
          "description": null,
          "value": "CRMINT",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "bq_dataset_id"
        },
        {
          "description": null,
          "value": "output",
          "label": null,
          "is_required": false,
          "type": "string",
          "name": "bq_table_id"
        }
      ],
      "id": "1de006a76d7c40489bb740b0157fbb5c",
      "name": "GA REPORT TO BQ"
    },
  ],

Cheers

**Comment by Slony** [comment]
Hi bmind,

From your job config I see that you're querying Core Reporting API for the following metrics and dimensions:

- `ga:users`
- `ga:source`
- `ga:date`

`GAToBQImporter` worker expects you to have the following fields in a BigQuery table used for output:

- `ga_users` — INTEGER
- `ga_source` — STRING
- `ga_date` — STRING

To allow for maximum flexibility, `GAToBQImporter` worker looks for BigQuery table fields named after Google Analytics dimensions and metrics used in your Core Reporting API query and fills in the fields with matching names with values fetched form Google Analytics. It leaves all other fields untouched with `NULL`s as their values.

As long as BigQuery doesn't accept filed names with colons `:`, you should replace them with underscores `_` in the names of dimensions and metrics. For example, `ga:users` metric should correspond to `ga_users` field in BigQuery table, `ga:source` dimension should correspond to `ga_source` field and so on.

In addition to metrics and dimensions that you fetch from Google Analytics, `GAToBQImporter` worker will try to find and fill in the following fields:

- `view_id` — Google analytics view ID
- `start_date` — the first date of the period for which current report was created
- `end_date` — the last date of the period for which current report was created

`view_id` field can help you to identify the view from which the data was fetched in case you specified more than one view ID in "View IDs" parameter of the job.

`start_date` and `end_date` could be very useful for the following reasons:

1. If you check "Fetch data day by day" checkbox, then `GAToBQImporter` worker will requests a separate report for each day of the period specified by "Start date" and "End date" job parameters. In this case you would most likely want to have the date for each row of data, and hence you will use `start_date` field or `end_date` field — both fields will have the same date as the reports would be fetched for every single day.
2. `GAToBQImporter` worker never overwrites the data in a BigQuery table — it always appends the data to the table. If you don't truncated the table, then the data will be accumulated in the table, and you would most likely want to have `start_date` and `end_date` fields to keep track of dates for which you requested the data from Google Analytics.

Please, don't hesitate to ask more questions regarding `GAToBQImporter` worker or let me know if I can close this issue.

Thanks!
