### ISSUE TITLE
Usage and Cost Estimation

### ISSUE THREAD

**Issue by daniel-zuckerberg** [google/crmint#363]
Usage and costs from CRMint will primarily be driven by BigQuery queries for deployments with large datasets. As such, can you incorporate the query dry run feature so that there is a way to understand the expected usage and costs before recurring jobs are deployed by CRMint?

Reference: https://cloud.google.com/bigquery/docs/dry-run-queries

**Comment by instant-bqml** [comment]
Dry Run functionality was added to the BQScriptExecutor worker in https://github.com/google/crmint/pull/364 and is now incorporated in the master branch.

**Comment by dulacp** [comment]
Thanks @daniel-zuckerberg for the initial feedback.
The PR #364 has been merged as stated above, it's now part of the solution.
