### ISSUE TITLE
"Fetch data day by day" 

### ISSUE THREAD

**Issue by garanj** [google/crmint#40]
An option in GAToBQImporter - what does this mean?

**Comment by Slony** [comment]
Hey Garan,

Thank you for your question!

You can find an answer in [this comment](https://github.com/google/crmint/issues/33#issuecomment-426950742).

Quick quote:

> If you check "Fetch data day by day" checkbox, then `GAToBQImporter` worker will requests a separate report for each day of the period specified by "Start date" and "End date" job parameters. In this case you would most likely want to have the date for each row of data, and hence you will use `start_date` field or `end_date` field — both fields will have the same date as the reports would be fetched for every single day.

Hope it helps.

Cheers!

_Alex P._
