### ISSUE TITLE
Pipeline seems running but nothing shows up in BQ 

### ISSUE THREAD

**Issue by yongpuitung** [google/crmint#400]
Hi team,

When I tried to run the model training pipeline on CRMint using Instant BQML template with all required information, the pipeline seems to be running as below. However, the dataset and model cannot be found in Bigquery. 

![pipeline](https://user-images.githubusercontent.com/115608996/211011227-f70945c9-d621-4aec-94fa-e5383b22c0ca.png)

Wonder if its a connection issue? but I have provided all information in the Instant BQML template. May I know if its necessary to fill in the setting here?

![setting](https://user-images.githubusercontent.com/115608996/211011886-6f16bc1e-673d-4765-bc35-e2709ddedad9.png)

Thanks a lot.

**Comment by instant-bqml** [comment]
Thanks for letting us know. We've submitted some patches to resolve this issue.

I would recommend `git pull` any new changes and then re-run `crmint bundle install` to re-deploy CRMint.

If it is a completely fresh install, you can just execute 
`source <(curl -Ls https://raw.githubusercontent.com/google/crmint/master/scripts/install.sh) && crmint bundle install`

**Comment by dulacp** [comment]
Hi @yongpuitung,

Thanks to your feedback we were able to act quickly on it and fix this bug that was affecting new deployments.

The root issue was that our containers (controller, jobs) were pinned to the 3.0 version, whereas the deployment code (Terraform behind the scene) was configuring an updated authentication mechanism for our Pub/Sub topics. This resulted in the containers not able to verify the signatures of these Pub/Sub requests and rejected them with a 400 status.

On top of that, we observed a timeout issue with long running tasks like yours. This is now fixed and you can safely **update your CRMint deployment by using the [update instructions in the Wiki](https://github.com/google/crmint/wiki/Update-CRMint-to-the-latest-version)**.

Let us know if you encounter any other issue!

Cheers,
Pierre

**Comment by yongpuitung** [comment]
I am trying to install CRMint again and run the command 
`source <(curl -Ls https://raw.githubusercontent.com/google/crmint/master/scripts/install.sh) && crmint bundle install`
but there is another error saying "ModuleNotFoundError: No module named 'backend'". Please advise. Thanks.

Besides, as I want to see how GA4 sends data to BQ, I have manually run all the steps in "training pipeline" and some steps in "prediction pipeline". Before I figure out how to use CRMint, can you advise how I can run "send events to GA4", "Audience Boundaries" & "Publish/Update GA4 Audience" manually?
