### ISSUE TITLE
"Don't create table if doesn't exist"

### ISSUE THREAD

**Issue by garanj** [google/crmint#41]
In StorageToBQImporter

Double negatives confuse me :-)
Does this mean "Require table to already exist" ?
Or is it slightly different?

**Comment by Slony** [comment]
Hey Garan,

Thank you for noticing this! 

"_Don't create table if doesn't exist_" parameter checked corresponds to `CREATE_NEVER` value for `configuration.load.createDisposition` parameter in [representation of a BigQuery job](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#resource-representations):

> `CREATE_NEVER`: The table must already exist. If it does not, a 'notFound' error is returned in the job result.

So, I agree: it's better to rename the parameter to "_Require table to already exist_" — we'll fix it soon.

Cheers!

_Alex P._
