### ISSUE TITLE
BQToMeasurementProtocolGA4 - GA4 Measurement Protocol JSON template

### ISSUE THREAD

**Issue by TondaHavlik** [google/crmint#429]
Hi, is there any example how GA4 Measurement Protocol JSON template should look like? How to connect this template with BQ table and corresponding columns?
```
{
"client_id":"${client_id}",
"user_id":"${user_id}",
"timestamp_micros":"${timestamp_micros}",
"non_personalized_ads":false,
  "events":[{
     "name":"${name}",
     "params":{
       "order_id":"${order_id}",
       "currency":"${currency}",
       "value":"${value}",
       "type":"${type}",
       "session_id":"${session_id}"}
}]
}
```
Thanks for help.

**Comment by instant-bqml** [comment]
Hi there,
Here's an [example](https://i.imgur.com/O6xMZzZ.png) BQToMeasurementProtocolGA4 setup. And then here is the [BigQuery table](https://i.imgur.com/Sl6SYfF.png) that populates the JSON template. Effectively, each column in the BigQuery table can be dynamically inserted in the `${variable}` in the JSON template. 

Also check out [Instant BQML](https://instant-bqml.appspot.com/) for CRMint templates using GA4 data for marketing activation.

**Comment by TondaHavlik** [comment]
Thanks. Helped.
