### ISSUE TITLE
Deploy Guide: Open in Cloud Shell button doesn't handle digits correctly

### ISSUE THREAD

**Issue by OriginalAlias** [google/crmint#58]
The Open Cloud Shell button doesn't always activate when digits are present in the Cloud Project Name. Seen in the deploy guide at [Deploy CRMint Quickstart](https://google.github.io/crmint/docs/quickstart/index.html#run-setup-steps-on-cloud-shell).

Works: crmint-3
Fails: crmint-3n
Fails: crmin-n3

![image](https://user-images.githubusercontent.com/6906635/48625873-52ef6b80-e9a8-11e8-9262-1eddc1d6207f.png)

**Comment by Slony** [comment]
Fixed with [Fix Cloud Project ID regex](https://github.com/google/crmint/commit/9a0f5a64339c5ea8a906837e1755654498638c2a).
