### ISSUE TITLE
Scheduled pipelines getting stuck at 'running'

### ISSUE THREAD

**Issue by benpowis** [google/crmint#64]
Recently I have upgraded my CRMint installation and added several new pipelines, since this change I have experienced pipelines getting stuck on 'running' for several hours, requiring manual stopping.

If I stop the pipelines and restart them manually, they complete successfully.

Here are some screenshots from the jobs:

![image](https://i.postimg.cc/XqqCkyZk/2018-11-23-11-36-47.jpg)

![image](https://i.postimg.cc/qRjKKG77/2018-11-23-11-37-39.jpg)

![image](https://i.postimg.cc/0Q8mr4P3/2018-11-23-11-37-55.jpg)

![image](https://i.postimg.cc/tgdWqbQW/2018-11-23-11-38-13.jpg)

**Comment by dulacp** [comment]
We've fixed the implementation to avoid such rare cases in the PR #66

@benpowis, can you please [update your CRMint instance](https://github.com/google/crmint/wiki/Update-CRMint-from-the-dev-branch) with the latest `dev` version?

Cheers
