### ISSUE TITLE
Error from gcloud in deployment guide

### ISSUE THREAD

**Issue by garanj** [google/crmint#96]
When running the [deployment guide](https://google.github.io/crmint/docs/quickstart/index.html) the final step to launch CRMint in a browser fails:

```
garan@cloudshell:~/crmint (my-project-name)$ gcloud app browse
Traceback (most recent call last):
  File "/google/google-cloud-sdk/lib/gcloud.py", line 20, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
garan@cloudshell:~/crmint (my-project-name)$
```

**Comment by mcarchon** [comment]
Running the command from root directory seemed to do the trick.
First type `$ cd` to get to your root directory. In your case you should then see `garan@cloudshell:` instead of `garan@cloudshell:~/crmint`. Then enter the command `gcloud app browse`.

**Comment by shinobe-atobe** [comment]
mcarrchon's solution doesnt solve the issue. Cannot use any gcloud functions without getting the same error

**Comment by jiakuanATF** [comment]
Same issue here. Tried to run it from both user folder and root directory, and neither worked. Any update or advice?
